httpTimeout: 300000

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs

packageExtensions:
  "@iobroker/adapter-react-v5@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
      "@mui/system": "*"
