httpTimeout: 300000

packageExtensions:
  "iobroker.vis-widgets-trashmaster@*":
    peerDependencies:
      typescript: "*"
  "@craco/craco@*":
    peerDependencies:
      typescript: "*"
      "@types/node": "*"
      postcss: "*"
  "craco-module-federation@*":
    peerDependencies:
      react-scripts: "*"
      "@types/node": "*"
      postcss: "*"
      typescript: "*"
  "eslint-config-react-app@*":
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "@iobroker/vis-2-widgets-react-dev@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "react-scripts@*":
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "craco-esbuild@*":
    peerDependencies:
      esbuild: "*"
      webpack: "*"
